app_id: "7dc6285a-83e3-4a27-a883-fc01a006c93c"
app_secret: "UVX1.1g77MT3E3f.HmNzZlDP.uh3mG9~QF"
redirect: "http://localhost:8000/callback"
scopes: "openid profile offline_access user.read calendars.read"
authority: "https://login.microsoftonline.com/common"
authorize_endpoint: "/oauth2/v2.0/authorize"
token_endpoint: "/oauth2/v2.0/token"
